# This workflow will setup Python, run unittests, and execute verify_mapfile.py.

name: Verify mapfile.csv

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  verify-mapfile:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/scripts/ci/verify_mapfile

    steps:
    - name: Checkout perfmon
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Python 3.x
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: "3.x"

    - name: Install Python packages
      run: pip install -r requirements.txt

    - name: Run verify_mapfile self tests
      run: python -m unittest

    - name: Validate mapfile.csv
      run: python verify_mapfile.py
